services:
  postgres:
    image: postgres:15
    container_name: db_container
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: btp_tokens

volumes:
  postgres_data: