package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"errors"
)

// Transfer is the resolver for the transfer field.
func (r *mutationResolver) Transfer(ctx context.Context, fromAddress string, toAddress string, amount int32) (int32, error) {
	if amount <= 0 {
		return 0, errors.New("Amount must be positive")
	}

	tx, err := r.DB.Beginx()
	if err != nil {
		return 0, err
	}
	defer tx.Rollback()

	// If transferring to self, just check balance and return it
	if fromAddress == toAddress {
		var balance int32
		err = tx.Get(&balance, "SELECT balance FROM wallets WHERE address = $1 FOR UPDATE", fromAddress)
		if err != nil {
			return 0, errors.New("Wallet not found")
		}
		if balance < amount {
			return 0, errors.New("Insufficient balance")
		}
		return balance, nil
	}

	// Lock wallets alphabetically to prevent deadlocks
	firstLock := fromAddress
	secondLock := toAddress

	if fromAddress > toAddress {
		firstLock = toAddress
		secondLock = fromAddress
	}
	var temp int32
	var fromBalance int32
	var errFirst, errSecond error

	errFirst = tx.Get(&temp, "SELECT balance FROM wallets WHERE address = $1 FOR UPDATE", firstLock)
	if firstLock == fromAddress {
		fromBalance = temp
	}
	errSecond = tx.Get(&temp, "SELECT balance FROM wallets WHERE address = $1 FOR UPDATE", secondLock)
	if secondLock == fromAddress {
		fromBalance = temp
	}

	// Check if sender wallet exists and has sufficient balance
	if firstLock == fromAddress && errFirst != nil || secondLock == fromAddress && errSecond != nil {
		return 0, errors.New("Sender wallet not found")
	}
	if fromBalance < amount {
		return 0, errors.New("Insufficient balance")
	}

	// If destination wallet does not exist, create it
	if errFirst != nil && firstLock == toAddress {
		_, err = tx.Exec("INSERT INTO wallets (address, balance) VALUES ($1, $2)", firstLock, 0)
		if err != nil {
			return 0, err
		}
	}
	if errSecond != nil && secondLock == toAddress {
		_, err = tx.Exec("INSERT INTO wallets (address, balance) VALUES ($1, $2)", secondLock, 0)
		if err != nil {
			return 0, err
		}
	}

	newSenderBalance := fromBalance - amount
	_, err = tx.Exec("UPDATE wallets SET balance = balance - $1 WHERE address = $2", amount, fromAddress)
	if err != nil {
		return 0, err
	}
	_, err = tx.Exec("UPDATE wallets SET balance = balance + $1 WHERE address = $2", amount, toAddress)
	if err != nil {
		return 0, err
	}

	return newSenderBalance, tx.Commit()
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
