package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"errors"
)

// Transfer is the resolver for the transfer field.
func (r *mutationResolver) Transfer(ctx context.Context, fromAddress string, toAddress string, amount int32) (int32, error) {
	if amount <= 0 {
		return 0, errors.New("amount must be positive")
	}

	tx, err := r.DB.BeginTxx(ctx, nil)
	if err != nil {
		return 0, err
	}
	defer tx.Rollback()

	// This locks existing rows AND creates/locks new ones in one go.
	upsertStmt := `
        INSERT INTO wallets (address, balance) VALUES ($1, 0)
        ON CONFLICT (address) DO UPDATE SET address = EXCLUDED.address
        RETURNING balance`

	// 2. Handle Self-Transfer
	if fromAddress == toAddress {
		var balance int32
		err := tx.GetContext(ctx, &balance, upsertStmt, fromAddress)
		if err != nil {
			return 0, err
		}
		return balance, tx.Commit()
	}

	// Lock wallets alphabetically to prevent deadlocks
	addrs := []string{fromAddress, toAddress}
	if fromAddress > toAddress {
		addrs[0], addrs[1] = addrs[1], addrs[0]
	}
	var fromBalance int32
	for _, addr := range addrs {
		var bal int32
		if err := tx.GetContext(ctx, &bal, upsertStmt, addr); err != nil {
			return 0, err
		}
		if addr == fromAddress {
			fromBalance = bal
		}
	}

	// Check sufficient balance
	if fromBalance < amount {
		return 0, errors.New("insufficient balance")
	}

	newSenderBalance := fromBalance - amount
	_, err = tx.Exec("UPDATE wallets SET balance = balance - $1 WHERE address = $2", amount, fromAddress)
	if err != nil {
		return 0, err
	}
	_, err = tx.Exec("UPDATE wallets SET balance = balance + $1 WHERE address = $2", amount, toAddress)
	if err != nil {
		return 0, err
	}

	return newSenderBalance, tx.Commit()
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
